package com.example.application.views.personaldetails;

import com.example.application.views.MainLayout;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Hr;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.EmailField;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.server.auth.AnonymousAllowed;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;

@PageTitle("Personal details")
@Route(value = "person-form", layout = MainLayout.class)
@AnonymousAllowed
@Uses(Icon.class)
public class PersonaldetailsView extends Composite<VerticalLayout> {

    public PersonaldetailsView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H3 h3 = new H3();
        FormLayout formLayout2Col = new FormLayout();
        TextField textField = new TextField();
        TextField textField2 = new TextField();
        DatePicker datePicker = new DatePicker();
        TextField textField3 = new TextField();
        EmailField emailField = new EmailField();
        TextField textField4 = new TextField();
        TextField textField5 = new TextField();
        TextField textField6 = new TextField();
        Hr hr = new Hr();
        H3 h32 = new H3();
        FormLayout formLayout2Col2 = new FormLayout();
        TextField textField7 = new TextField();
        TextField textField8 = new TextField();
        TextField textField9 = new TextField();
        Hr hr2 = new Hr();
        H2 h2 = new H2();
        HorizontalLayout layoutRow = new HorizontalLayout();
        TextField textField10 = new TextField();
        Hr hr3 = new Hr();
        FormLayout formLayout2Col3 = new FormLayout();
        TextField textField11 = new TextField();
        TextField textField12 = new TextField();
        TextField textField13 = new TextField();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Button buttonSecondary = new Button();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        getContent().setJustifyContentMode(JustifyContentMode.START);
        getContent().setAlignItems(Alignment.CENTER);
        layoutColumn2.setWidth("100%");
        layoutColumn2.setMaxWidth("800px");
        layoutColumn2.setHeight("min-content");
        h3.setText("Personal Information");
        h3.setWidth("100%");
        formLayout2Col.setWidth("100%");
        textField.setLabel("Full Name");
        textField2.setLabel("Date of Birth");
        datePicker.setLabel("Gender");
        textField3.setLabel("Marital Status");
        emailField.setLabel("Occupation");
        textField4.setLabel("Address");
        textField4.setWidth("291px");
        textField5.setLabel("Phone Number");
        textField5.setWidth("min-content");
        textField6.setLabel("Email Address");
        textField6.setWidth("min-content");
        h32.setText("Emergency Contact");
        h32.setWidth("max-content");
        formLayout2Col2.setWidth("100%");
        textField7.setLabel("Name");
        textField7.setWidth("352px");
        textField8.setLabel("Relationship");
        textField8.setWidth("352px");
        textField9.setLabel("Phone Number");
        textField9.setWidth("352px");
        h2.setText("Medical Information");
        h2.setWidth("max-content");
        layoutRow.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.getStyle().set("flex-grow", "1");
        textField10.setLabel("Primary Care Physician");
        textField10.setWidth("352px");
        formLayout2Col3.setWidth("100%");
        textField11.setLabel("Allergies");
        textField11.setWidth("min-content");
        textField12.setLabel("Chronic Condition");
        textField12.setWidth("min-content");
        textField13.setLabel("Previous Surgeries");
        textField13.setWidth("min-content");
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.getStyle().set("flex-grow", "1");
        buttonPrimary.setText("Save");
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonSecondary.setText("Cancel");
        buttonSecondary.setWidth("min-content");
        getContent().add(layoutColumn2);
        layoutColumn2.add(h3);
        layoutColumn2.add(formLayout2Col);
        formLayout2Col.add(textField);
        formLayout2Col.add(textField2);
        formLayout2Col.add(datePicker);
        formLayout2Col.add(textField3);
        formLayout2Col.add(emailField);
        formLayout2Col.add(textField4);
        formLayout2Col.add(textField5);
        formLayout2Col.add(textField6);
        layoutColumn2.add(hr);
        layoutColumn2.add(h32);
        layoutColumn2.add(formLayout2Col2);
        formLayout2Col2.add(textField7);
        formLayout2Col2.add(textField8);
        formLayout2Col2.add(textField9);
        layoutColumn2.add(hr2);
        layoutColumn2.add(h2);
        layoutColumn2.add(layoutRow);
        layoutRow.add(textField10);
        layoutColumn2.add(hr3);
        layoutColumn2.add(formLayout2Col3);
        formLayout2Col3.add(textField11);
        formLayout2Col3.add(textField12);
        formLayout2Col3.add(textField13);
        layoutColumn2.add(layoutRow2);
        layoutRow2.add(buttonPrimary);
        layoutRow2.add(buttonSecondary);
    }
}
